Repository mongdol-beach/MHMH-Frontend, pull requests merged in 2024-12, with the labels that each got.

#7 feat: 메인 페이지 작업
  .github/workflows/auto-review-assign-pr.yml
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/.gitkeep
  src/assets/icons/main-background-effect.svg
  src/components/.gitkeep
  src/components/Layout/index.tsx
  src/components/Layout/styled.ts
  src/components/Main/MainLinkBox/MainLink/index.tsx
  src/components/Main/MainLinkBox/MainLink/styled.ts
  src/components/Main/MainLinkBox/index.tsx
  src/components/Main/MainLinkBox/styled.ts
  src/components/Main/index.tsx
  src/components/Main/styled.ts
  src/constants/path.ts
  src/pages/MainPage.tsx
  src/styles/color.ts
  src/styles/global.ts
  src/styles/theme.ts
  tsconfig.json
  vite.config.ts
Labels: ⚙ feat

#10 feat: 상황 선택 페이지 추가
  src/App.tsx
  src/assets/icons/icon-arrow.svg
  src/assets/icons/icon-home.svg
  src/components/Layout/styled.ts
  src/components/Main/MainLinkBox/MainLink/styled.ts
  src/components/Main/MainLinkBox/index.tsx
  src/components/Main/styled.ts
  src/components/Situation/Header/index.tsx
  src/components/Situation/Header/styled.ts
  src/components/Situation/data.ts
  src/components/Situation/index.tsx
  src/components/Situation/styled.ts
  src/constants/path.ts
  src/pages/SituationPage.tsx
  src/styles/global.ts
  vercel.json
Labels: ⚙ feat

#13 Feat/situation page
  src/assets/icons/home.svg
  src/assets/icons/left-arrow.svg
  src/components/Situation/Header/index.tsx
  src/components/Situation/Header/styled.ts
  src/components/Situation/styled.ts
Labels: ⚙ feat

#15 [refactor] 메인, 상황 선택 페이지 수정
  src/components/Header/index.tsx
  src/components/Header/styled.ts
  src/components/Main/MainLinkBox/MainLink/index.tsx
  src/components/Main/MainLinkBox/MainLink/styled.ts
  src/components/Main/MainLinkBox/index.tsx
  src/components/Situation/data.ts
  src/components/Situation/index.tsx
  src/components/Situation/styled.ts
  src/styles/color.ts
Labels: 💻 refactor

#17 [refactor] 메인, 상황별 주제 페이지 디자인 수정
  src/assets/icons/main-background-effect.svg
  src/components/Main/styled.ts
  src/components/Situation/index.tsx
  src/components/Situation/styled.ts
  src/styles/color.ts
Labels: 💻 refactor

#19 feat: 상황별 토픽 페이지 추가
  global.d.ts
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/axios.ts
  src/components/Main/MainLinkBox/index.tsx
  src/components/Situation/data.ts
  src/components/Situation/index.tsx
  src/components/TopicsBySituation/data.ts
  src/components/TopicsBySituation/index.tsx
  src/components/TopicsBySituation/styled.ts
  src/components/TopicsBySituation/type.ts
  src/constants/path.ts
  src/pages/TopicsBySituationPage.tsx
  src/types/situation.ts
  tsconfig.app.json
Labels: ⚙ feat

#22 Feat/topic finish
  src/App.tsx
  src/assets/icons/close.svg
  src/components/Main/MainLinkBox/index.tsx
  src/components/RandomTopics/index.tsx
  src/components/Situation/index.tsx
  src/components/SituationFinish/SummaryModal.tsx
  src/components/SituationFinish/index.tsx
  src/components/SituationFinish/styled.ts
  src/components/TopicCards/index.tsx
  src/components/TopicsBySituation/index.tsx
  src/constants/path.ts
  src/elements/Modal.tsx
  src/hooks/useModal.tsx
  src/hooks/useSituations.ts
  src/hooks/useTopicsBySituation.ts
  src/styles/color.ts
  src/styles/font.ts
Labels: ⚙ feat

#26 [feat] 상황별 토픽 리스트 페이지 작업
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/api.ts
  src/assets/icons/blue-circle.svg
  src/assets/icons/card-back.svg
  src/assets/icons/card-background-effect.svg
  src/assets/icons/card-dot-effect.svg
  src/assets/icons/flip.svg
  src/assets/icons/quotes-end.svg
  src/assets/icons/quotes-start.svg
  src/assets/icons/semi-circle.svg
  src/assets/icons/smile.svg
  src/assets/icons/tip-text.svg
  src/components/Card/CardBack/index.tsx
  src/components/Card/CardBack/styled.ts
  src/components/Card/CardFront/index.tsx
  src/components/Card/CardFront/styled.ts
  src/components/Card/index.tsx
  src/components/Card/styled.ts
  src/components/Header/styled.ts
  src/components/Modal/TopicCardModal/index.tsx
  src/components/Modal/TopicCardModal/styled.ts
  src/components/Modal/index.tsx
  src/components/Modal/styled.ts
  src/components/Portal/index.tsx
  src/components/SituationFinish/styled.ts
  src/components/TopicList/Topic/index.tsx
  src/components/TopicList/Topic/styled.ts
  src/components/TopicList/index.tsx
  src/components/TopicList/styled.ts
  src/constants/path.ts
  src/constants/queryKey.ts
  src/hooks/.gitkeep
  src/hooks/useGetTopicList.ts
  src/pages/TopicListPage.tsx
  src/pages/index.ts
  src/styles/color.ts
  src/types/index.ts
Labels: ⚙ feat

#27 feat: 상황별 토픽 추천 Header title 변경
  src/assets/icons/short-arrow.svg
  src/components/TopicsBySituation/index.tsx
  src/components/TopicsBySituation/styled.ts
  src/hooks/useTopicsBySituation.ts
Labels: ⚙ feat

#28 feat: 상황별 토픽 둘러보기 버튼에 link 추가
  src/components/TopicsBySituation/index.tsx
Labels: ⚙ feat

#31 feat: 카드 교체
  src/components/RandomTopics/data.ts
  src/components/RandomTopics/index.tsx
  src/components/TopicCards/index.tsx
  src/components/TopicCards/styled.ts
  src/components/TopicsBySituation/data.ts
  src/components/TopicsBySituation/styled.ts
  src/types/topic.ts
Labels: ⚙ feat

#30 feat/topic-finish 완성
  src/components/Modal/SituationFinishModal/Modal.tsx
  src/components/SituationFinish/SummaryModal.tsx
  src/components/SituationFinish/index.tsx
  src/components/SituationFinish/styled.ts
  src/styles/color.ts
  src/types/topic.ts
Labels: ⚙ feat

#18 feat: 밸런스게임 페이지 추가
  src/App.tsx
  src/components/BalanceGame/Header/index.tsx
  src/components/BalanceGame/Header/styled.ts
  src/components/BalanceGame/data.ts
  src/components/BalanceGame/index.tsx
  src/components/BalanceGame/styled.ts
  src/components/Main/styled.ts
  src/components/Situation/styled.ts
  src/components/SituationFinish/styled.ts
  src/components/TopicsBySituation/styled.ts
  src/hooks/getRandomBalance.ts
  src/pages/BalanceGamePage.tsx
  src/styles/color.ts
  src/types/balance.ts
Labels: ⚙ feat, 🛠️ fix

#33 [feat] 메타 태그 적용
  index.html
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  public/og-image.png
  public/robots.txt
  src/apis/api.ts
  src/hooks/useGetTopicList.ts
  src/pages/MainPage.tsx
  src/pages/RandomTopicsPage.tsx
  src/pages/SituationPage.tsx
  src/pages/TopicListPage.tsx
  src/pages/TopicsBySituationPage.tsx
Labels: ⚙ feat

#36 feat: add loading component
  src/assets/images/loading.gif
  src/components/BalanceGame/index.tsx
  src/components/Loading/index.tsx
  src/components/Loading/styled.ts
  src/components/RandomTopics/index.tsx
  src/components/Situation/index.tsx
  src/components/TopicsBySituation/index.tsx
  src/hooks/useGetTopicList.ts
  src/pages/TopicListPage.tsx
Labels: ⚙ feat

#39 fix: height가 812px보다 작을 때 가운데 부분만 보이는 이슈 해결
  src/components/Layout/styled.ts
Labels: 🛠️ fix

#40 [feat] 토픽 리스트 페이지 suspense 적용
  src/App.tsx
  src/hooks/useGetTopicList.ts
  src/pages/TopicListPage.tsx
Labels: ⚙ feat

#41 다음 문제로 넘어가지 않는 현상 수정, color파일에 변수 추가, 밸런스 게임 피그마 UI로 수정, header 컴포넌트 UI로 수정
  src/components/BalanceGame/Header/styled.ts
  src/components/BalanceGame/index.tsx
  src/components/BalanceGame/styled.ts
  src/styles/color.ts
Labels: ⚙ feat

#43 5번째 선택지 누르고 버튼 활성화되도록 수정, 선택 후 선택지 못 누르게 하도록 수정
  src/components/BalanceGame/index.tsx
  src/components/BalanceGame/styled.ts
Labels: 🛠️ fix

#45 feat: 카드 뒤집을 때 뒤의 카드가 보이지 않도록 수정
  src/components/TopicCards/index.tsx
  src/components/TopicCards/styled.ts
Labels: ⚙ feat

#38 Feat/error page
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Error/index.tsx
  src/components/Error/styled.ts
  src/hooks/useSituations.ts
Labels: ⚙ feat

#47 fix: 모달 높이 수정~
  src/components/Modal/styled.ts
Labels: 🛠️ fix

#49 fix: pc기준 height 812px로 고정
  src/components/Layout/styled.ts
Labels: 🛠️ fix

#51 fix: 선택지 누른 후에 버튼 활성화
  src/components/BalanceGame/index.tsx
Labels: 🛠️ fix

#53 fix: 모달 및 버튼 위치
  src/components/Modal/TopicCardModal/index.tsx
  src/components/Modal/TopicCardModal/styled.ts
Labels: 🛠️ fix

#58 [feat] gtm 연결하기
  package.json
  pnpm-lock.yaml
  src/App.tsx
Labels: ⚙ feat

#60 fix: 모바일 환경에서 밸런스 게임 선택지 선택 후 배경색이 남아 있는 현상, 텍스트가 위로 올라가는 현상 수정
  package.json
  src/components/BalanceGame/index.tsx
  src/components/BalanceGame/styled.ts
  src/hooks/getRandomBalance.ts
Labels: 🛠️ fix
