Repository mongdol-beach/MHMH-Frontend, pull requests merged in 2025-01, with the labels that each got.

#62 [refactor] 메인 페이지 디자인 수정
  src/assets/icons/main-background-effect.svg
  src/assets/icons/main-logo.svg
  src/assets/icons/right-arrow.svg
  src/components/Layout/index.tsx
  src/components/Layout/styled.ts
  src/components/Main/MainLinkBox/styled.ts
  src/components/Main/index.tsx
  src/components/Main/styled.ts
  src/components/TopicList/styled.ts
  src/styles/color.ts
  src/styles/global.ts
Labels: 💻 refactor

#68 Feat/topic finish
  global.d.ts
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/icons/HomeIcon.tsx
  src/assets/icons/logo.svg
  src/assets/icons/re-start.svg
  src/assets/icons/share-kakao.svg
  src/assets/icons/share.svg
  src/components/Layout/styled.ts
  src/components/Modal/SituationFinishModal/Modal.tsx
  src/components/Modal/index.tsx
  src/components/SituationFinish/SummaryModal.tsx
  src/components/SituationFinish/index.tsx
  src/components/SituationFinish/styled.ts
  src/components/Toast/index.tsx
  src/components/TopicsBySituation/styled.ts
  src/hooks/useModal.ts
  src/styles/font.ts
  src/types/balance.ts
  src/types/global.d.ts
  src/types/index.ts
  src/types/situation.ts
  src/types/swiper.d.ts
  src/types/topic.ts
Labels: ⚙ feat

#72 feat: 공유하기 element dataset 추가
  src/components/SituationFinish/index.tsx
Labels: ⚙ feat

#73 fix: 모바일 환경 hover effect 제거
  src/components/Situation/styled.ts
Labels: 🛠️ fix

#70 Feat/feedback modal
  src/apis/api.ts
  src/assets/icons/bad-off.svg
  src/assets/icons/bad-on.svg
  src/assets/icons/good-off.svg
  src/assets/icons/good-on.svg
  src/assets/icons/soso-off.svg
  src/assets/icons/soso-on.svg
  src/components/Main/index.tsx
  src/components/Modal/FeedbackModal/index.tsx
  src/components/Modal/FeedbackModal/styled.ts
  src/components/Modal/SummaryModal/ styled.ts
  src/components/Modal/SummaryModal/index.tsx
  src/components/Modal/TopicCardModal/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/styled.ts
  src/components/SituationFinish/index.tsx
  src/components/SituationFinish/styled.ts
Labels: ⚙ feat

#75 feat: 화살표 네비게이션 버튼 추가
  src/components/Card/CardFront/styled.ts
  src/components/Card/index.tsx
  src/components/TopicCards/index.tsx
  src/components/TopicCards/styled.ts
  src/components/TopicsBySituation/styled.ts
Labels: ⚙ feat

#78 feat: 랜덤 토픽 api 개수 제한 제거
  src/components/CardDeck/index.tsx
  src/components/RandomTopicCards/index.tsx
  src/components/RandomTopics/index.tsx
  src/components/RandomTopics/styled.ts
  src/components/TopicCards/index.tsx
  src/components/TopicCards/styled.ts
  src/hooks/getRandomTopics.ts
  src/hooks/useRandomTopics.ts
  src/hooks/useTopicCardNavigation.ts
Labels: ⚙ feat
