Repository mongdol-beach/MHMH-Frontend, pull requests merged in 2025-02, with the labels that each got.

#77 Feat/topic finish
  index.html
  src/components/SituationFinish/index.tsx
  src/types/global.d.ts
Labels: ⚙ feat

#79 [feat] 소셜 로그인 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/api.ts
  src/assets/icons/google.svg
  src/assets/icons/kakao.svg
  src/assets/icons/naver.svg
  src/components/Loading/index.tsx
  src/components/Loading/styled.ts
  src/components/Login/LoginList/index.tsx
  src/components/Login/LoginList/styled.ts
  src/components/Login/LoginText/index.tsx
  src/components/Login/LoginText/styled.ts
  src/components/Login/index.tsx
  src/components/Login/styled.ts
  src/constants/path.ts
  src/constants/token.ts
  src/hooks/useGetOAuthToken.ts
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/RandomTopicsPage.tsx
  src/pages/SituationPage.tsx
  src/pages/TopicListPage.tsx
  src/pages/TopicsBySituationPage.tsx
  src/pages/index.ts
  src/pages/login-redirect/oauth.tsx
  src/types/index.ts
  src/utils/.gitkeep
  src/utils/getOAuthPlatformFromPath.ts
Labels: ⚙ feat

#81 feat: clarity script 추가
  index.html
Labels: ⚙ feat

#84 토픽 카드페이지, 리스트페이지, 요약 모달 주제별 색상 변경, svg-> ts변환, 토픽카드 모달 닫기 Icon변경
  src/assets/icons/CardBackIcon.tsx
  src/assets/icons/CardBackgroundEffect.tsx
  src/assets/icons/CardDotEffect.tsx
  src/assets/icons/TipTextIcon.tsx
  src/assets/icons/blue-circle.svg
  src/assets/icons/cancle.svg
  src/assets/icons/semi-circle.svg
  src/assets/icons/smile.svg
  src/components/Card/CardBack/index.tsx
  src/components/Card/CardBack/styled.ts
  src/components/Card/CardFront/index.tsx
  src/components/Card/CardFront/styled.ts
  src/components/Card/index.tsx
  src/components/CardDeck/index.tsx
  src/components/Modal/SummaryModal/index.tsx
  src/components/Modal/SummaryModal/styled.ts
  src/components/Modal/TopicCardModal/index.tsx
  src/components/Modal/TopicCardModal/styled.ts
  src/components/RandomTopicCards/index.tsx
  src/components/RandomTopics/index.tsx
  src/components/SituationFinish/index.tsx
  src/components/SituationFinish/styled.ts
  src/components/TopicCards/index.tsx
  src/components/TopicList/Topic/index.tsx
  src/components/TopicList/Topic/styled.ts
  src/components/TopicList/index.tsx
  src/components/TopicsBySituation/index.tsx
  src/components/TopicsBySituation/styled.ts
  src/hooks/useRandomTopics.ts
  src/hooks/useTopicsBySituation.ts
  src/pages/TopicListPage.tsx
  src/types/index.ts
  src/types/topic.ts
Labels: ⚙ feat, 🛠️ fix

#91 refactor: OptionPercentBackground animation 컴포넌트화
  package.json
  pnpm-lock.yaml
  src/assets/lottie/loading-three-dots.json
  src/components/AnimatedOptionPercentBackground/index.tsx
  src/components/AnimatedOptionPercentBackground/styled.ts
  src/components/BalanceGame/index.tsx
  src/components/BalanceGame/styled.ts
  src/components/LoadingThreeDotsLottie/index.tsx
Labels: 💻 refactor

#94 [refactor] 메인 페이지 일러스트 수정
  .github/pull_request_template.md
  .github/workflows/auto-review-assign-pr.yml
  src/assets/icons/main-background-effect.svg
  src/assets/icons/main-effect1.svg
  src/assets/icons/main-effect2.svg
  src/assets/icons/main-effect3.svg
  src/components/BalanceGame/styled.ts
  src/components/Main/MainLinkBox/MainLink/index.tsx
  src/components/Main/MainLinkBox/MainLink/styled.ts
  src/components/Main/MainLinkBox/index.tsx
  src/components/Main/MainLinkBox/styled.ts
  src/components/Modal/styled.ts
  src/styles/color.ts
  src/styles/global.ts
Labels: 💻 refactor
